elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
  volumes:
  - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
kibana:
  image: kibana
  ports:
   - "5601:5601"
  links:
   - elasticsearch
logstash:
  image: logstash
  command: logstash -f /config/logstash.conf
  volumes_from:
   - application
  volumes:
   - ./config/logstash:/config
  ports:
   - "5043:5043"
   - "5044:5044"
  links:
   - elasticsearch
application:
  build: proctor
  volumes:
   - /var/log:/var/log
  ports:
   - "8090:8080"

